### ISSUE TITLE
This project is being 'managed' by a github newbie 'me' - Helpful advice/links please

### ISSUE THREAD

**Issue by Vertfromage** [Vertfromage/ManFight#13]
So opened this project up for Hacktoberfest, and I've gotten lots of contributors and it's great and fun, but I've discovered that I have no idea about merge conflicts.

I know what they are, but I've been using github in the browser and with github desktop and I'm not sure about how to resolve them using github desktop and I have git bash on my computer but I've barely touched it so it's a bit intimidating to use.  

I use intellij for the java programming course I've been using and I know there's a tool in it that allows me to compare files in it, can I use that to resolve the conflicts before pushing to github from github desktop?

**Comment by AlexDvorak** [comment]
[How to resolve PRs on Github](https://help.github.com/en/articles/resolving-a-merge-conflict-on-github)
[How PRs work in general](https://help.github.com/en/articles/about-pull-request-merges)
The tool you're probably thinking of in IntelliJ is documented [here](https://www.jetbrains.com/help/idea/resolving-conflicts.html#distributed-version-control-systems) but generally, resolving on Github is easier

**Comment by Vertfromage** [comment]
Thank you, AlexDvorak.  Thankfully so far people have resolved the conflicts themselves, which is good because the resolve conflicts button wasn't working and I would have had to use the command line and that seemed intimidating.  I should probably do a github minicourse on udemy or something because I've read a couple articles and played around with it but I still feel confused.
