### ISSUE TITLE
Incorporate Insults.java into manfight or add extra insults to Insults.java

### ISSUE THREAD

**Issue by Vertfromage** [Vertfromage/ManFight#15]
I started a branch with Insults.java that adds more fun dialogue to the game but I haven't tried to incorporate it into the Man class yet, the easiest way to do that would be to add a new attack called insult and use the isScared within isInjured in a similar way to how roar is used.  Maybe have the one being insulted respond by laughing with a weak insult, or with a mean one saying "well that's mean, but your insults won't stop me", but set isScared true with awesomeInsults and maybe say, "Wow, I don't know what to say!" or something funnier. 

For beginners looking for a safe way to contribute adding more insults is easy.

**Comment by erinshick** [comment]
I'd like to try this, can you assign it to me?

**Comment by Vertfromage** [comment]
It's all yours.  I merged the branch into the master since it's just one file.

**Comment by Vertfromage** [comment]
Good job, yours is merged to the master, the code I forgot to save before commiting the file is in the insults branch again if you want to take a look... I'm going to have a careful read of your code and see if we can combine the code nicely.
