### ISSUE TITLE
Add funny Insults to Insults.java Beginners Only. 

### ISSUE THREAD

**Issue by Vertfromage** [Vertfromage/ManFight#20]
Super easy for new coders.  In the interest of learning please also read through the core java files to try to understand how things work... they are in the src/main/java/com/crystal folder... it makes it more fun when you know how things work.  Then add a new insult to one of the three categories of weak, mean or awesome insults.

**Comment by iamkavinarasu** [comment]
> Super easy for new coders. In the interest of learning please also read through the core java files to try to understand how things work... they are in the src/main/java/com/crystal folder... it makes it more fun when you know how things work. Then add a new insult to one of the three categories of weak, mean or awesome insults.

Can I work on this? Thank you!

**Comment by Neuron34** [comment]
i would like to work on this  issue

**Comment by IJustDev** [comment]
We should nominate you for an award.
