### ISSUE TITLE
Implement a summon monster attack in Fighter.java 

### ISSUE THREAD

**Issue by Vertfromage** [Vertfromage/ManFight#31]
So I thought it might be fun to give fighters the ability to summon a monster.  The way I envision this is:

- fighter summons monster
- other fighter is asked: Do you want to summon a monster too or try and take on this monster on your own?
- If they summon a monster the two monsters go head to head and one wins which then attacks a random limb on the character before leaving. 
- If they don't they can attack the monster and it's randomly decided if they frighten off the monster or the monster attacks a random limb.

There is already a Monster.java file that will help with implementing this idea.  If you want to implement this or a part of it please claim in comments and I'll assign you.

**Comment by MrinaliniU** [comment]
Hello @Vertfromage can I work on this please? :)

**Comment by Vertfromage** [comment]
Sure MrinaliniU, thanks!
